name: missing-trees
services:
  missing_trees:
    build: .
    ports:
      - "8080:8080"
    environment:
      FLASK_ENV: production
      PYTHONPATH: /app
    command: >
      gunicorn --bind 0.0.0.0:8080 src.app:app --access-logfile - --error-logfile - --log-level debug

# {RL 02/07/25} https://www.composerize.com/