BOTTOM_BUFFER_MULTIPLIER=3.5
DEFAULT_GEOGRAPHIC_CRS = "EPSG:4326"
DEFAULT_PROJECTED_CRS = 32734  # South Africa / Cape Town UTM Zone 34S
LEFT_BUFFER_MULTIPLIER=3
NORMAL_BUFFER_MULTIPLIER=2
OVERLAP_THRESHOLD_METRES=7.2
TREE_SPACING=4.0

TREE_RADIUS_MULTIPLIER = 0.4
GRID_SPACING_MULTIPLIER = 0.75
MIN_DISTANCE_MULTIPLIER = 0.8
MAX_DISTANCE_MULTIPLIER = 2.5
NEARBY_SEARCH_MULTIPLIER = 1.5
MAX_NEARBY_TREES = 4
HIGH_CONFIDENCE_DISTANCE_THRESHOLD = 4.5
