DEFAULT_GEOGRAPHIC_CRS = "EPSG:4326"
DEFAULT_PROJECTED_CRS = 32734  # South Africa / Cape Town UTM Zone 34S
TREE_SPACING=4.0
BOTTOM_BUFFER_MULTIPLIER=3.5
LEFT_BUFFER_MULTIPLIER=3
NORMAL_BUFFER_MULTIPLIER=2
OVERLAP_THRESHOLD_METRES=7.2